services:
  # --- INFRASTRUCTURE ---
  postgres-db:
    image: postgres:15-alpine
    container_name: pf-postgres
    environment:
      POSTGRES_DB: polyglot_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
    ports:
      - "5432:5432"
    networks:
      - polyglot-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d polyglot_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3.11-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - polyglot-net

  redis:
    image: redis:alpine
    container_name: pf-redis
    networks:
      - polyglot-net

  # --- MICROSERVICES ---

  # JAVA: Core Engine
  order-service:
    build: ./order-service
    container_name: order-service
    ports:
      - "8080:8080"
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/polyglot_db
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=password123
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      rabbitmq:
        condition: service_healthy
      postgres-db:
        condition: service_healthy # Espera o Postgres ficar pronto
    networks:
      - polyglot-net

  # PYTHON: Intelligence Service
  analytics-service:
    build: ./analytics-service
    container_name: pf-python-analytics
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq/
      - DB_HOST=postgres-db
      - DB_NAME=polyglot_db
      - DB_USER=admin
      - DB_PASS=password123
    depends_on:
      - rabbitmq
      - postgres-db
    networks:
      - polyglot-net

  # PHP: Customer Portal (BFF)
  customer-portal:
    build: ./customer-portal
    container_name: pf-php-web
    ports:
      - "8000:80"
    volumes:
      - ./customer-portal:/var/www/html
    environment:
      - APP_ENV=local
      - APP_KEY=base64:0oTb4vtktWJQ1cCQCE/faLuvu1Cg+HV0MN3UZrUjCYs=
      - ORDER_SERVICE_URL=http://order-service:8080
      - REDIS_HOST=pf-redis
    networks:
      - polyglot-net

networks:
  polyglot-net:
    driver: bridge