spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/polyglot_db}
    username: admin
    password: password123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  
  # Configuração de Mensageria
  cloud:
    stream:
      bindings:
        orderCreated-out-0:
          destination: order-events-exchange
          content-type: application/json
      rabbit:
        bindings:
          orderCreated-out-0:
            producer:
              routing-key-expression: '''order.created'''